{% set name = "torchgeo" %}
{% set version = "0.7.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torchgeo-{{ version }}.tar.gz
  sha256: 4ba0e96ea826080f393b1bb719a3f8c364637112710b1ac38c56b9590a638e29

build:
  entry_points:
    - torchgeo = torchgeo.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}
    - einops >=0.3
    - fiona >=1.8.22
    - kornia >=0.7.4
    - lightly >=1.4.5,!=1.4.26
    - lightning >=2,!=2.3.*,!=2.5.0
    - matplotlib-base >=3.6
    - numpy >=1.23.2
    - pandas >=1.5
    - pillow >=9.2
    - pyproj >=3.4
    - rasterio >=1.3.3,!=1.4.0,!=1.4.1,!=1.4.2
    - rtree >=1.0.1
    - segmentation-models-pytorch >=0.3.3
    - shapely >=1.8.5
    - timm >=0.9.2
    - pytorch >=2
    - torchmetrics >=1.2
    - torchvision >=0.15.1
    - typing-extensions >=4.5

    # Needed by LightningCLI
    - jsonargparse >=4.27.7
    - typeshed-client >=2.1

test:
  imports:
    - torchgeo
    - torchgeo.datamodules
    - torchgeo.datasets
    - torchgeo.losses
    - torchgeo.models
    - torchgeo.samplers
    - torchgeo.trainers
    - torchgeo.transforms
  commands:
    - pip check
    - torchgeo --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/microsoft/torchgeo
  license: MIT
  license_file: LICENSE
  summary: 'TorchGeo: datasets, samplers, transforms, and pre-trained models for geospatial data'
  description: |
    TorchGeo is a PyTorch domain library, similar to torchvision, providing datasets, samplers, transforms, and pre-trained models specific to geospatial data.

    The goal of this library is to make it simple

    1. for machine learning experts to work with geospatial data, and
    2. for remote sensing experts to explore machine learning solutions.
  dev_url: https://github.com/microsoft/torchgeo
  doc_url: https://torchgeo.readthedocs.io/

extra:
  recipe-maintainers:
    - adamjstewart
    - calebrob6
    - isaaccorley
    - nilsleh
